// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikcfxzvtlkdrlzlokjdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrY2Z4enZ0bGtkcmx6bG9ramRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjA5NzYsImV4cCI6MjA2NTk5Njk3Nn0.qNQZ5Vhmu7Tdrcymuk8vUe6sm4AZ-P31AwzBlpSE0I4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);